from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
DATA_DIR = PROJECT_ROOT / "data"
IMAGES_DIR = DATA_DIR / "images"
VIDEOS_DIR = DATA_DIR / "videos"
FLIGHT_RECORDS_DIR = DATA_DIR / "flight_records"
LOGS_DIR = PROJECT_ROOT / "logs"

TELLO_IP = "192.168.10.1"
TELLO_PORT = 8889
TELLO_VIDEO_PORT = 11111
TELLO_STATE_PORT = 8890

WIFI_SSID = "RMTT-A93874"

CONNECTION_TIMEOUT = 10
COMMAND_TIMEOUT = 5
MAX_RETRY_ATTEMPTS = 3

FLIGHT_ALTITUDE_LIMIT = 500
SPEED_LIMIT = 200                            # 增加单次移动距离限制以支持实验
BATTERY_WARNING_THRESHOLD = 20
BATTERY_CRITICAL_THRESHOLD = 10

VIDEO_FPS = 30
VIDEO_RESOLUTION = (960, 720)
IMAGE_QUALITY = 95

DEFAULT_FLIGHT_HEIGHT = 100
DEFAULT_MOVEMENT_DISTANCE = 50
DEFAULT_ROTATION_ANGLE = 90

LOG_LEVEL = "INFO"
ENABLE_SAFETY_CHECKS = True
AUTO_LAND_ON_LOW_BATTERY = True
AUTO_LAND_ON_CONNECTION_LOST = True

# 自动保存设置
AUTO_SAVE_ON_EXIT = True
CREATE_SESSION_BACKUP = True
GENERATE_SESSION_REPORT = True

# 数据记录设置
ENABLE_FLIGHT_DATA_RECORDING = True
FLIGHT_DATA_RECORDING_INTERVAL = 0.02  # 记录间隔(秒) - 50Hz频率
FLIGHT_DATA_CSV_ENCODING = 'utf-8-sig'  # CSV文件编码